# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='familyevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='familyevent',
            name='index',
        ),
        migrations.RemoveField(
            model_name='familyevent',
            name='year',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='index',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='year',
        ),
        migrations.RemoveField(
            model_name='timelineimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timelineimage',
            name='index',
        ),
        migrations.RemoveField(
            model_name='timelineimage',
            name='year',
        ),
        migrations.RemoveField(
            model_name='timelinestory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timelinestory',
            name='index',
        ),
        migrations.RemoveField(
            model_name='timelinestory',
            name='year',
        ),
        migrations.AddField(
            model_name='familyevent',
            name='timelineentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.TimelineEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='timelineentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.TimelineEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='timelineentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.TimelineEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelinestory',
            name='timelineentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.TimelineEntry'),
            preserve_default=False,
        ),
    ]
