# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events_published', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
