# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20161225_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
